# set(CPACK_GENERATOR "DEB")

# set(CPACK_DEBIAN_PACKAGE_MAINTAINER "nombre <correo>")
# set(CPACK_DEBIAN_PACKAGE_VENDOR "IES")

# set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Descripción")
# set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
# set(CPACK_DEBIAN_PACKAGE_DEPENDS "catu (>= 2.1.1), cabina-settings (>= 1.0.0)")
# set(CPACK_DEBIAN_PACKAGE_PRIORITY "required")
# set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
# set(CPACK_PACKAGE_VERSION "${SERVER_VERSION_STR}")
# set(CPACK_PACKAGE_VERSION_MAJOR "${SERVER_VERSION_MAJOR}")
# set(CPACK_PACKAGE_VERSION_MINOR "${SERVER_VERSION_MINOR}")
# set(CPACK_PACKAGE_VERSION_PATCH "${SERVER_VERSION_REVISION}")
# set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_SOURCE_DIR}/recursos/postinst;${CMAKE_CURRENT_SOURCE_DIR}/recursos/postrm;${CMAKE_CURRENT_SOURCE_DIR}/recursos/prerm;")

# include(CPack)
