set(SERVER_VERSION 0x010000)
set(SERVER_VERSION_MAJOR 1)
set(SERVER_VERSION_MINOR 0)
set(SERVER_VERSION_REVISION 0)

set(SERVER_VERSION_STR ${SERVER_VERSION_MAJOR}.${SERVER_VERSION_MINOR}.${SERVER_VERSION_REVISION})
set(SERVER_VERSION_CSTR \"${SERVER_VERSION_MAJOR}.${SERVER_VERSION_MINOR}.${SERVER_VERSION_REVISION}\")

include_directories( ${CMAKE_BINARY_DIR} include build )

set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

set(CMAKE_CXX_FLAGS -std=c++11)

add_definitions( -Wall -O3 -DSERVER_VERSION=${SERVER_VERSION} -DSERVER_VERSION_STR=${SERVER_VERSION_CSTR} )
